language: perl
perl:
   - "5.30.0"
   - "5.28.2"
   - "5.22.4"
   - "5.18.4"
   - "5.16.3"
   - "5.14.4"
   - "5.12.5"
   - "5.10.1"

before_install:
   - export HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
   - cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
   - cpanm -n Devel::Cover::Report::Coveralls

install:
   cpanm -q -n --installdeps .

script:
   perl Build.PL && ./Build build && cover -test -report coveralls
